trigger:
- branch-name

pool:
  vmImage: windows-latest

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/*.csproj'
  project: '**/*.sln'

steps:
- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'NuGet Tool Installer'

- task: NuGetCommand@2
  name: 'NuGetCommand'
  displayName: 'NuGet Command Restore'
  inputs:
    command: restore
    restoreSolution: '$(solution)'
    feedsToUse: select

- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '8.x'

- task: DotNetCoreCLI@2
  name: 'DotNetCoreCLI'
  displayName: 'DotNet Project Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration)'

- task: AzureRmWebAppDeployment@4
  name: 'AzureRmWebAppDeployment'
  displayName: 'Azure WebApp Deployment'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'service-connection-name'
    appType: 'webApp'
    WebAppName: 'app-service-name'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    enableCustomDeployment: true
    DeploymentType: webDeploy
    AdditionalArguments: '-verbose'
